version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
